spring:
  application:
    name: app-core

  profiles:
    active: default

  # 외부 설정 파일 import
  config:
    import:
      - optional:file:../config/application.yml
      - optional:file:../config/${spring.application.name}/application.yml
      - optional:file:../config/${spring.application.name}/application-${spring.profiles.active}.yml
