spring:
  application:
    name: app-core

  profiles:
    active: default
    
  datasource:
    url: jdbc:mariadb://localhost:3306/groupware?useUnicode=true&characterEncoding=utf8mb4&serverTimezone=Asia/Seoul
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:qwer1234}
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 5000  # 5초로 단축
      idle-timeout: 600000
      max-lifetime: 1800000
      initialization-fail-timeout: 1  # 빠른 실패
  
  flyway:
    enabled: false
    baseline-on-migrate: true
    locations: classpath:db/migration/core
    schemas: core
    table: schema_version
    validate-on-migrate: true
      
  jackson:
    time-zone: Asia/Seoul
    serialization:
      write-dates-as-timestamps: false
      
server:
  port: 8080
  servlet:
    context-path: /api/v1
    
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    default-fetch-size: 100
    default-statement-timeout: 30
    cache-enabled: false
    use-generated-keys: true
  mapper-locations: classpath:kr/co/platform/**/*.xml
  type-aliases-package: kr.co.platform.core.**.entity, kr.co.platform.core.**.dto
  
logging:
  level:
    root: INFO
    kr.co.platform: DEBUG
    org.springframework.web: INFO
    org.springframework.boot: INFO
    org.springframework.boot.autoconfigure: INFO
    com.zaxxer.hikari: INFO
    org.mybatis: DEBUG
    jdbc.sqlonly: DEBUG
    
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
      
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
  show-actuator: true
  default-produces-media-type: application/json
  default-consumes-media-type: application/json