# app-core 개발 환경 설정

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/groupware?useUnicode=true&characterEncoding=utf8mb4&serverTimezone=Asia/Seoul
    username: root
    password: qwer1234
    
logging:
  level:
    root: INFO
    kr.co.platform: DEBUG
    org.springframework.web: DEBUG
    org.springframework.boot: INFO
    org.mybatis: DEBUG
    jdbc.sqlonly: DEBUG
    
springdoc:
  swagger-ui:
    enabled: true
    
common:
  file:
    base-path: c:/platform/files  # Windows 개발 환경용 경로