# app-core 운영 환경 설정

spring:
  datasource:
    url: jdbc:mariadb://${CORE_DB_HOST:localhost}:${CORE_DB_PORT:3306}/${CORE_DB_NAME:groupware}?useUnicode=true&characterEncoding=utf8mb4&serverTimezone=Asia/Seoul
    username: ${CORE_DB_USERNAME}
    password: ${CORE_DB_PASSWORD}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      
logging:
  level:
    root: WARN
    kr.co.platform: INFO
    org.springframework: WARN
    org.mybatis: WARN
    
springdoc:
  swagger-ui:
    enabled: false  # 운영 환경에서는 Swagger UI 비활성화
  api-docs:
    enabled: false
    
management:
  endpoints:
    web:
      exposure:
        include: health,metrics  # 운영 환경에서는 최소한의 엔드포인트만 노출
        
common:
  file:
    base-path: /opt/platform/files  # Linux 운영 환경용 경로