spring:
  application:
    name: app.streamhub
    
  profiles:
    active: dev
    
  datasource:
    url: jdbc:mariadb://localhost:3306/streamhub?useUnicode=true&characterEncoding=utf8mb4&serverTimezone=Asia/Seoul
    username: ${DB_USERNAME:groupware}
    password: ${DB_PASSWORD:qwer1234}
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  flyway:
    enabled: false
    baseline-on-migrate: true
    locations: classpath:db/migration/streamhub
    schemas: streamhub
    table: schema_version
    validate-on-migrate: true
    
  jackson:
    time-zone: Asia/Seoul
    serialization:
      write-dates-as-timestamps: false
      
server:
  port: 8081
  servlet:
    context-path: /streamhub
    
websocket:
  endpoint: /ws
  allowed-origins: "*"
  
logging:
  level:
    kr.co.groupware.streamhub: DEBUG
    org.springframework.web.socket: DEBUG
    
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always