spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/groupware?useUnicode=true&characterEncoding=utf8mb4&serverTimezone=Asia/Seoul
    username: groupware
    password: groupware123
    
logging:
  level:
    kr.co.groupware: DEBUG
    org.springframework.web: DEBUG
    org.mybatis: DEBUG
    jdbc: DEBUG
    jdbc.sqlonly: DEBUG
    jdbc.sqltiming: INFO
    jdbc.resultsettable: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"